apiVersion: v1
kind: Service
metadata:
  name: {{ include "agedigitaltwins.fullname" . }}
  labels:
    {{- include "agedigitaltwins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "agedigitaltwins.name" . }}-api
