{{- if .Values.backups.endpointCA.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backups.endpointCA.name | default (printf "%s-ca-bundle" (include "agedigitaltwins.fullname" .)) | quote }}
data:
  {{ .Values.backups.endpointCA.key | default "ca-bundle.crt" | quote }}: {{ .Values.backups.endpointCA.value }}
  
{{- end }}
