apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agedigitaltwins.fullname" . }}-events
  labels: {{- include "agedigitaltwins.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {{- toJson .Values.events.config | nindent 4 }}
