apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agedigitaltwins.fullname" . }}-events
  labels:
    {{- include "agedigitaltwins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agedigitaltwins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.events.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agedigitaltwins.labels" . | nindent 8 }}
        {{- with .Values.events.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.events.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.events.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.events.securityContext | nindent 12 }}
          image: "{{- include "agedigitaltwins.events.imageName" . }}"
          ports:
            - containerPort: 8080
          env:
            - name: AGEDB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "agedigitaltwins.fullname" . }}-app
                  key: port
            - name: AGEDB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "agedigitaltwins.fullname" . }}-app
                  key: dbname
            - name: AGEDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "agedigitaltwins.fullname" . }}-app
                  key: username
            - name: AGEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "agedigitaltwins.fullname" . }}-app
                  key: password
            - name: ConnectionStrings__agedb
              value: "Server={{ include "agedigitaltwins.fullname" . }}-r;Port=$(AGEDB_PORT);Database=$(AGEDB_NAME);Username=$(AGEDB_USERNAME);Password=$(AGEDB_PASSWORD)"
          livenessProbe:
            {{- toYaml .Values.events.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.events.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.events.resources | nindent 12 }}
          {{- with .Values.events.volumeMounts }}
          volumeMounts:
            - name: config-volume
              mountPath: /app
              subPath: appsettings.json
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "agedigitaltwins.fullname" . }}-events
            items:
            - key: appsettings.json
              path: appsettings.json
      {{- with .Values.events.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.events.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.events.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.events.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
