{{- if not (empty .Values.cluster.monitoring.customQueries) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agedigitaltwins.fullname" . }}-monitoring
  namespace: {{- .Release.Namespace -}}
  labels:
    cnpg.io/reload: ""
    {{- include "agedigitaltwins.labels" . | nindent 4 }}
data:
  custom-queries: |
    {{- range .Values.cluster.monitoring.customQueries }}
    {{ .name }}:
      query: {{ .query | quote }}
      metrics:
        {{- .metrics | toYaml | nindent 8 }}
    {{- end }}
{{- end }}