apiVersion: v2
name: db-query-operator
description: A Helm chart for deploying the KtrlPlane Database Query Kubernetes operator
home: https://github.com/konnektr-io/db-query-operator
sources:
  - https://github.com/konnektr-io/db-query-operator
maintainers:
  - name: Konnektr.io
    url: https://github.com/konnektr-io
    email: info@konnektr.io
  - name: nikoraes
    url: https://github.com/nikoraes
keywords:
  - kubernetes-operator
  - database
  - query
  - CRD
  - PostgreSQL
version: 0.9.1
appVersion: "0.9.1"
annotations:
  crd-repo-url: "https://api.github.com/repos/konnektr-io/db-query-operator/contents/config/crd/bases?ref=v{{ .appVersion }}"
