apiVersion: v1
kind: Service
metadata:
  name: ktrlplane-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ktrlplane-backend
  ports:
    - port: 8080
      targetPort: 8080
