{{- if and .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ktrlplane-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ktrlplane-db
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}