apiVersion: v1
kind: Service
metadata:
  name: ktrlplane-frontend-service
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: ktrlplane-frontend
  ports:
    - port: 80
      targetPort: 80
