name: Publish Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for chart in $(find . -name Chart.yaml -exec dirname {} \;); do
            helm package $chart --destination packaged
          done

      - name: Upload chart packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chart-packages
          path: packaged/

  update-gh-pages:
    runs-on: ubuntu-latest
    needs: package-charts

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download chart packages artifact
        uses: actions/download-artifact@v4
        with:
          name: chart-packages

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Update Helm repo index
        run: |
          helm repo index . --url https://charts.konnektr.io

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm chart repository" || echo "No changes to commit"
          git push origin gh-pages
