name: Publish Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Pull existing gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || echo "gh-pages branch does not exist yet"
          mkdir -p packaged
          if [ -d gh-pages ]; then
            cp -r gh-pages/* packaged/
          fi

      - name: Package Helm charts
        run: |
          for chart in $(find . -name Chart.yaml -exec dirname {} \;); do
            helm package $chart --destination packaged
          done

      - name: Update Helm repo index
        run: |
          helm repo index packaged --url https://charts.konnektr.io

      - name: Push to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Clean up untracked files to avoid conflicts
          git clean -fd
          # Switch to gh-pages branch
          git checkout -b gh-pages || git checkout gh-pages
          # Copy packaged files and commit changes
          cp -r packaged/* .
          git add .
          git commit -m "Update Helm chart repository" || echo "No changes to commit"
          git push origin gh-pages
